## Set the API endpoint used to create the Service resource.
apiVersion: v1
## Define the type of the resource.
kind: Service
## Set the parameters that make the object identifiable, such as its name, namespace, and labels.
metadata:
  labels:
    app: techtrends
  name: techtrends
  namespace: {{ .Values.namespace.name }}
## Define the desired configuration for the Service resource.
spec:
  ## Define the ports that the service should serve on. 
  ports:
  - port: {{ .Values.ports.port }}
    protocol: {{ .Values.ports.protocol }}
    targetPort: {{ .Values.ports.targetPort }}
  ## Identify the pods managed by this Service using the following selectors.
  ## In this case, all pods with the label `techtrends`.
  selector:
    app: techtrends
  ## Define the Service type, here set to ClusterIP.
  type: {{ .Values.type }}

